---
- name: Deploy
  hosts: all
  gather_facts: no
  vars:
    keep_releases: 5
    git_repo: "https://github.com/kosmatov/knight-bot"
    git_branch: "master"
  roles:
    - app
  tasks:
    - import_tasks: tasks/deploy.yml
