---
- name: Remove DEPLOY_UNFINISHED
  file: state=absent path={{ release_path.stdout }}/DEPLOY_UNFINISHED

- name: Clean up releases
  shell: ls -1dt {{ releases_path.stdout }}/* | tail -n +$(({{ keep_releases }} + 1)) | xargs rm -rf
  when: keep_releases > 0
