---
- name: Reload systemd daemon
  shell: systemctl daemon-reload
  when: update_services

- name: Restart rsyslog
  shell: systemctl restart rsyslog
  when: update_services

- name: Restart services
  shell: systemctl restart kbot-{{ item }}
  with_items: "{{ profiles }}"
